# Error Handling

In [1]:
a

NameError: name 'a' is not defined

In [2]:
1/0

ZeroDivisionError: division by zero

In [ ]:
1 + 'a'

In [3]:
if True print('a')

SyntaxError: invalid syntax (<ipython-input-3-19321a870d74>, line 1)

In [4]:
# Syntax

try:
    pass
except:
    pass
    

In [5]:
try:
    print(1/0)
except ZeroDivisionError:
    print(f"can't divide by zero")

can't divide by zero


In [6]:
try:
    print(1/0)
except ZeroDivisionError as error:
    print(f"can't divide by zero due this --> {error}")

can't divide by zero due this --> division by zero


In [7]:
import ana

ModuleNotFoundError: No module named 'ana'

In [8]:
try:
    import ana
except:
    print("Okay")
    

Okay


In [9]:
import unittest

In [10]:
def add(x, y):
    return x+y

In [11]:
class TestAdd(unittest.TestCase):

    def test_add(self):
        self.assertEqual(add(4, 5), 9)
        self.assertEqual(add(3, 3), 6)


In [12]:
a = TestAdd()

In [13]:
a

<__main__.TestAdd testMethod=runTest>

In [14]:
a.test_add()

## Pandas and numpy

In [15]:
import numpy as np

In [16]:
a = [2, 4, 6]

In [17]:
[i*2 for i in a]

[4, 8, 12]

In [18]:
a*2

[2, 4, 6, 2, 4, 6]

In [19]:
%%time
l = [i*2 for i in range(1, 1000000)]

CPU times: user 79.6 ms, sys: 19.9 ms, total: 99.5 ms
Wall time: 98.1 ms


In [22]:
arr = list(range(1, 1000000))

In [24]:
np_array = np.array(arr)

In [25]:
np_array

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [26]:
ar = np.arange(1, 1000000)

In [27]:
ar

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [28]:
ar

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [30]:
%%time
ar*2

CPU times: user 5.23 ms, sys: 165 µs, total: 5.4 ms
Wall time: 7.74 ms


array([      2,       4,       6, ..., 1999994, 1999996, 1999998])

In [32]:
max([1, 2, 4])

4

In [34]:
max(ar)

999999

In [35]:
a = [2, 3, 44, 5]

In [36]:
arr = np.array(a)

In [37]:
arr.mean()

13.5

In [38]:
arr.max()

44

In [39]:
arr.argmax()

2

In [40]:
arr.argmin()

0

In [43]:
np.median(arr)

4.0

In [45]:
a = np.random.rand(1, 100)

In [46]:
a.ndim

2

In [47]:
a

array([[0.55416813, 0.10611117, 0.77187265, 0.33699798, 0.73159472,
        0.34300516, 0.62487821, 0.96049355, 0.86549031, 0.61128346,
        0.52115159, 0.18829946, 0.74644067, 0.67127798, 0.03705504,
        0.89176032, 0.78820657, 0.5746785 , 0.03717476, 0.09547365,
        0.88941537, 0.1507207 , 0.1048959 , 0.77865722, 0.50090583,
        0.50011691, 0.56210632, 0.31115887, 0.48051672, 0.24686511,
        0.00293385, 0.27793381, 0.97664903, 0.08107283, 0.21955217,
        0.29274122, 0.72080581, 0.62570544, 0.31926367, 0.72752344,
        0.84685747, 0.50905147, 0.45588042, 0.19070838, 0.87817433,
        0.23892771, 0.68043923, 0.23868463, 0.16256856, 0.89029504,
        0.98049297, 0.96025424, 0.0754703 , 0.70859318, 0.79939937,
        0.21951593, 0.525239  , 0.74699663, 0.994233  , 0.16116048,
        0.83447382, 0.5041716 , 0.95347721, 0.53706291, 0.34978711,
        0.72194258, 0.16397206, 0.2456201 , 0.16663958, 0.66807017,
        0.85598593, 0.04177402, 0.99132818, 0.13

In [49]:
a[0].ndim

1

In [50]:
a.flatten()

array([0.55416813, 0.10611117, 0.77187265, 0.33699798, 0.73159472,
       0.34300516, 0.62487821, 0.96049355, 0.86549031, 0.61128346,
       0.52115159, 0.18829946, 0.74644067, 0.67127798, 0.03705504,
       0.89176032, 0.78820657, 0.5746785 , 0.03717476, 0.09547365,
       0.88941537, 0.1507207 , 0.1048959 , 0.77865722, 0.50090583,
       0.50011691, 0.56210632, 0.31115887, 0.48051672, 0.24686511,
       0.00293385, 0.27793381, 0.97664903, 0.08107283, 0.21955217,
       0.29274122, 0.72080581, 0.62570544, 0.31926367, 0.72752344,
       0.84685747, 0.50905147, 0.45588042, 0.19070838, 0.87817433,
       0.23892771, 0.68043923, 0.23868463, 0.16256856, 0.89029504,
       0.98049297, 0.96025424, 0.0754703 , 0.70859318, 0.79939937,
       0.21951593, 0.525239  , 0.74699663, 0.994233  , 0.16116048,
       0.83447382, 0.5041716 , 0.95347721, 0.53706291, 0.34978711,
       0.72194258, 0.16397206, 0.2456201 , 0.16663958, 0.66807017,
       0.85598593, 0.04177402, 0.99132818, 0.13003948, 0.08205

In [59]:
l = np.random.randint(3, 6, size=(3, 3))

In [60]:
l

array([[4, 3, 4],
       [3, 4, 3],
       [5, 5, 4]])

In [61]:
l.ndim

2

In [62]:
l.flatten()

array([4, 3, 4, 3, 4, 3, 5, 5, 4])

In [63]:
l.flatten().ndim

1

In [64]:
l.shape

(3, 3)

In [66]:
np.random.randn(5, 5)

array([[-0.9327229 ,  0.0182198 , -0.67321354,  1.68785636,  0.24140028],
       [-0.19402157,  1.46163922, -0.34970583,  0.57237365,  0.0796969 ],
       [-1.14129143,  0.83908791, -0.44843591, -1.11058162, -0.55621207],
       [ 0.46163263, -0.86327635, -0.49836994,  0.71159226, -0.08502439],
       [ 1.67774593,  0.27417064, -0.28140904, -1.26993539,  0.5258179 ]])

In [67]:
np.cos(40)

-0.6669380616522619

In [68]:
np.cos??

In [69]:
np.linspace(-3, 3, 1000)

array([-3.        , -2.99399399, -2.98798799, -2.98198198, -2.97597598,
       -2.96996997, -2.96396396, -2.95795796, -2.95195195, -2.94594595,
       -2.93993994, -2.93393393, -2.92792793, -2.92192192, -2.91591592,
       -2.90990991, -2.9039039 , -2.8978979 , -2.89189189, -2.88588589,
       -2.87987988, -2.87387387, -2.86786787, -2.86186186, -2.85585586,
       -2.84984985, -2.84384384, -2.83783784, -2.83183183, -2.82582583,
       -2.81981982, -2.81381381, -2.80780781, -2.8018018 , -2.7957958 ,
       -2.78978979, -2.78378378, -2.77777778, -2.77177177, -2.76576577,
       -2.75975976, -2.75375375, -2.74774775, -2.74174174, -2.73573574,
       -2.72972973, -2.72372372, -2.71771772, -2.71171171, -2.70570571,
       -2.6996997 , -2.69369369, -2.68768769, -2.68168168, -2.67567568,
       -2.66966967, -2.66366366, -2.65765766, -2.65165165, -2.64564565,
       -2.63963964, -2.63363363, -2.62762763, -2.62162162, -2.61561562,
       -2.60960961, -2.6036036 , -2.5975976 , -2.59159159, -2.58

In [70]:
import pandas as pd

In [75]:
a = {
    'key1': list('abcdef'),
    'key2': list(range(6)),
    'key3': list('ABCDEF')
}

In [76]:
df = pd.DataFrame(a)

In [77]:
a

{'key1': ['a', 'b', 'c', 'd', 'e', 'f'],
 'key2': [0, 1, 2, 3, 4, 5],
 'key3': ['A', 'B', 'C', 'D', 'E', 'F']}

In [78]:
df

key1  key2 key3
0    a     0    A
1    b     1    B
2    c     2    C
3    d     3    D
4    e     4    E
5    f     5    F

In [79]:
a['key1']

['a', 'b', 'c', 'd', 'e', 'f']

In [80]:
df['key1']

0    a
1    b
2    c
3    d
4    e
5    f
Name: key1, dtype: object

In [81]:
df['key2']

0    0
1    1
2    2
3    3
4    4
5    5
Name: key2, dtype: int64

In [82]:
arr = np.random.randn(100, 100)

In [86]:
np.eye(10, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [87]:
arr

array([[ 1.29628372,  0.60583609,  0.28628   , ...,  0.23734836,
        -1.5030094 , -0.27628795],
       [ 1.06597621,  1.08259602,  0.52336895, ...,  1.29374619,
         0.62554295,  0.10046377],
       [-0.26643797,  1.70505092, -0.04785583, ..., -1.26191642,
         1.32523823, -0.42854507],
       ...,
       [-0.74283663,  0.06889156,  0.21960693, ...,  0.58728265,
         0.44213068, -0.09103788],
       [ 0.53900221,  1.28200311, -1.02331776, ..., -0.04688747,
        -1.86775296,  0.00540184],
       [ 1.15126063,  0.47269605,  0.35698904, ...,  0.41484908,
        -0.22266306, -0.39631921]])

In [88]:
arr.shape

(100, 100)

In [89]:
arr.ndim

2

In [90]:
df = pd.DataFrame(arr)

In [91]:
df

0         1         2         3         4         5         6   \
0   1.296284  0.605836  0.286280 -1.603644 -0.933890 -0.245013  0.448170   
1   1.065976  1.082596  0.523369  0.392860  2.169864 -0.933146  0.073333   
2  -0.266438  1.705051 -0.047856  0.775636 -1.565388 -2.116412  0.330345   
3   0.013052 -1.249195  0.055326 -1.010466 -1.184311 -0.356834 -0.336943   
4   0.689750 -0.880364  0.664037 -0.514244  1.033128  1.596760  0.193006   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.535555  0.535315 -0.316394 -1.345825  0.985646 -0.280841  1.692374   
96 -0.208874  0.503362 -0.994804 -1.141338  0.144400 -1.139310 -0.536875   
97 -0.742837  0.068892  0.219607 -1.762436  0.192502 -0.084573  0.081371   
98  0.539002  1.282003 -1.023318  1.905679 -0.839147  1.025434 -1.663809   
99  1.151261  0.472696  0.356989 -0.468862 -0.296073  2.211698  0.407838   

          7         8         9   ...        90        91        92        93  \
0  -0.209419  0.289293  1.687889  ...  1.085550  0.361362  2.478867 -0.176082   
1   1.354769  1.558516  1.389750  ...  0.007539 -0.332405 -1.931087  0.381377   
2  -0.722211  2.317018 -1.122634  ...  0.279575 -0.682577  0.940564 -1.108417   
3   0.077229 -0.194452  0.048333  ...  1.791631 -0.681331 -2.061388  0.474097   
4   2.213407  0.814558 -0.561568  ... -0.023579 -0.963785 -0.737570  0.984158   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  2.236995  0.305292 -0.048202  ...  0.004992 -0.998164 -0.384085 -2.235665   
96  1.049218  1.978938 -0.557667  ... -0.073395 -0.717267  0.750956 -1.429442   
97 -0.119534  1.060109  0.330919  ...  1.211900  0.910360 -1.555058  0.149891   
98  1.280217  0.401399  2.902964  ... -0.748285 -0.963052  0.103504  0.311597   
99  0.415483  0.958924 -0.164693  ... -0.708794  0.409151 -0.033786  0.035134   

          94        95        96        97        98        99  
0  -0.078297  0.237853  1.527258  0.237348 -1.503009 -0.276288  
1  -0.596160  0.102534 -1.646820  1.293746  0.625543  0.100464  
2   0.166644 -1.020592 -1.311756 -1.261916  1.325238 -0.428545  
3   0.891958 -1.653039 -0.785182 -0.126184 -0.656143 -0.926092  
4   1.852040 -0.010209 -0.089483  1.307647  0.499279  0.030032  
..       ...       ...       ...       ...       ...       ...  
95 -1.191961  1.266627  0.505866 -1.204067 -0.017088 -1.493089  
96  0.440364  0.827207 -1.527539  0.554133 -0.432447 -0.978240  
97  1.466277  0.115172  0.853162  0.587283  0.442131 -0.091038  
98  0.899014  0.099926 -0.548970 -0.046887 -1.867753  0.005402  
99  0.555811 -0.346093 -1.671665  0.414849 -0.222663 -0.396319  

[100 rows x 100 columns]

In [92]:
df[:5]

0         1         2         3         4         5         6   \
0  1.296284  0.605836  0.286280 -1.603644 -0.933890 -0.245013  0.448170   
1  1.065976  1.082596  0.523369  0.392860  2.169864 -0.933146  0.073333   
2 -0.266438  1.705051 -0.047856  0.775636 -1.565388 -2.116412  0.330345   
3  0.013052 -1.249195  0.055326 -1.010466 -1.184311 -0.356834 -0.336943   
4  0.689750 -0.880364  0.664037 -0.514244  1.033128  1.596760  0.193006   

         7         8         9   ...        90        91        92        93  \
0 -0.209419  0.289293  1.687889  ...  1.085550  0.361362  2.478867 -0.176082   
1  1.354769  1.558516  1.389750  ...  0.007539 -0.332405 -1.931087  0.381377   
2 -0.722211  2.317018 -1.122634  ...  0.279575 -0.682577  0.940564 -1.108417   
3  0.077229 -0.194452  0.048333  ...  1.791631 -0.681331 -2.061388  0.474097   
4  2.213407  0.814558 -0.561568  ... -0.023579 -0.963785 -0.737570  0.984158   

         94        95        96        97        98        99  
0 -0.078297  0.237853  1.527258  0.237348 -1.503009 -0.276288  
1 -0.596160  0.102534 -1.646820  1.293746  0.625543  0.100464  
2  0.166644 -1.020592 -1.311756 -1.261916  1.325238 -0.428545  
3  0.891958 -1.653039 -0.785182 -0.126184 -0.656143 -0.926092  
4  1.852040 -0.010209 -0.089483  1.307647  0.499279  0.030032  

[5 rows x 100 columns]

In [95]:
df[-5:]

0         1         2         3         4         5         6   \
95  0.535555  0.535315 -0.316394 -1.345825  0.985646 -0.280841  1.692374   
96 -0.208874  0.503362 -0.994804 -1.141338  0.144400 -1.139310 -0.536875   
97 -0.742837  0.068892  0.219607 -1.762436  0.192502 -0.084573  0.081371   
98  0.539002  1.282003 -1.023318  1.905679 -0.839147  1.025434 -1.663809   
99  1.151261  0.472696  0.356989 -0.468862 -0.296073  2.211698  0.407838   

          7         8         9   ...        90        91        92        93  \
95  2.236995  0.305292 -0.048202  ...  0.004992 -0.998164 -0.384085 -2.235665   
96  1.049218  1.978938 -0.557667  ... -0.073395 -0.717267  0.750956 -1.429442   
97 -0.119534  1.060109  0.330919  ...  1.211900  0.910360 -1.555058  0.149891   
98  1.280217  0.401399  2.902964  ... -0.748285 -0.963052  0.103504  0.311597   
99  0.415483  0.958924 -0.164693  ... -0.708794  0.409151 -0.033786  0.035134   

          94        95        96        97        98        99  
95 -1.191961  1.266627  0.505866 -1.204067 -0.017088 -1.493089  
96  0.440364  0.827207 -1.527539  0.554133 -0.432447 -0.978240  
97  1.466277  0.115172  0.853162  0.587283  0.442131 -0.091038  
98  0.899014  0.099926 -0.548970 -0.046887 -1.867753  0.005402  
99  0.555811 -0.346093 -1.671665  0.414849 -0.222663 -0.396319  

[5 rows x 100 columns]

In [96]:
df.head()

0         1         2         3         4         5         6   \
0  1.296284  0.605836  0.286280 -1.603644 -0.933890 -0.245013  0.448170   
1  1.065976  1.082596  0.523369  0.392860  2.169864 -0.933146  0.073333   
2 -0.266438  1.705051 -0.047856  0.775636 -1.565388 -2.116412  0.330345   
3  0.013052 -1.249195  0.055326 -1.010466 -1.184311 -0.356834 -0.336943   
4  0.689750 -0.880364  0.664037 -0.514244  1.033128  1.596760  0.193006   

         7         8         9   ...        90        91        92        93  \
0 -0.209419  0.289293  1.687889  ...  1.085550  0.361362  2.478867 -0.176082   
1  1.354769  1.558516  1.389750  ...  0.007539 -0.332405 -1.931087  0.381377   
2 -0.722211  2.317018 -1.122634  ...  0.279575 -0.682577  0.940564 -1.108417   
3  0.077229 -0.194452  0.048333  ...  1.791631 -0.681331 -2.061388  0.474097   
4  2.213407  0.814558 -0.561568  ... -0.023579 -0.963785 -0.737570  0.984158   

         94        95        96        97        98        99  
0 -0.078297  0.237853  1.527258  0.237348 -1.503009 -0.276288  
1 -0.596160  0.102534 -1.646820  1.293746  0.625543  0.100464  
2  0.166644 -1.020592 -1.311756 -1.261916  1.325238 -0.428545  
3  0.891958 -1.653039 -0.785182 -0.126184 -0.656143 -0.926092  
4  1.852040 -0.010209 -0.089483  1.307647  0.499279  0.030032  

[5 rows x 100 columns]

In [97]:
df.head(10)

0         1         2         3         4         5         6   \
0  1.296284  0.605836  0.286280 -1.603644 -0.933890 -0.245013  0.448170   
1  1.065976  1.082596  0.523369  0.392860  2.169864 -0.933146  0.073333   
2 -0.266438  1.705051 -0.047856  0.775636 -1.565388 -2.116412  0.330345   
3  0.013052 -1.249195  0.055326 -1.010466 -1.184311 -0.356834 -0.336943   
4  0.689750 -0.880364  0.664037 -0.514244  1.033128  1.596760  0.193006   
5 -1.008867 -0.857929 -0.116234 -3.069809 -0.483098 -1.442161  0.016852   
6  1.606758 -0.848071  0.474212 -0.899776  0.147134  1.403666  1.232940   
7  1.588358 -0.926496  1.008237  0.036956 -1.492892 -0.599731  2.824315   
8  0.059154 -0.641031  1.806548 -0.230572  0.591997  0.483515  0.028741   
9 -1.031066 -0.162839 -0.483799  0.787264  0.461138  0.598508 -0.842000   

         7         8         9   ...        90        91        92        93  \
0 -0.209419  0.289293  1.687889  ...  1.085550  0.361362  2.478867 -0.176082   
1  1.354769  1.558516  1.389750  ...  0.007539 -0.332405 -1.931087  0.381377   
2 -0.722211  2.317018 -1.122634  ...  0.279575 -0.682577  0.940564 -1.108417   
3  0.077229 -0.194452  0.048333  ...  1.791631 -0.681331 -2.061388  0.474097   
4  2.213407  0.814558 -0.561568  ... -0.023579 -0.963785 -0.737570  0.984158   
5 -1.543806  0.140788  0.091351  ...  0.851331 -0.182765 -0.679845 -2.011999   
6  0.146922 -0.058361 -0.708178  ... -0.286342 -0.513345 -1.686664 -0.471980   
7 -1.702827 -0.780084  1.076220  ...  1.523778 -0.511955  0.221180  0.050096   
8 -1.653015  2.319999  1.573562  ...  1.133362  0.447362 -0.022945  0.388402   
9 -0.507701 -0.230474  0.990564  ... -0.629348  0.899026  0.897602 -0.882487   

         94        95        96        97        98        99  
0 -0.078297  0.237853  1.527258  0.237348 -1.503009 -0.276288  
1 -0.596160  0.102534 -1.646820  1.293746  0.625543  0.100464  
2  0.166644 -1.020592 -1.311756 -1.261916  1.325238 -0.428545  
3  0.891958 -1.653039 -0.785182 -0.126184 -0.656143 -0.926092  
4  1.852040 -0.010209 -0.089483  1.307647  0.499279  0.030032  
5 -0.920477  0.567726  0.653890 -0.172415 -0.474617 -2.690463  
6 -0.361986 -0.644995 -0.123197 -0.065375 -0.214012  0.277685  
7  0.184218 -1.579023  0.815629 -0.952175  0.653018 -0.982962  
8 -0.807881  0.635353  1.274550 -0.268017 -0.436478 -2.501098  
9 -0.028868  0.263726  0.024761 -0.157756  0.911498  0.404751  

[10 rows x 100 columns]

In [98]:
df.tail(10)

0         1         2         3         4         5         6   \
90  0.477932  0.163731  0.993451 -1.795053 -0.741696  1.141408  0.355518   
91 -2.765682  0.127772 -0.089838  2.555683 -2.780739 -0.281038 -0.222094   
92  0.678806  0.338715  1.216825 -0.447565 -0.757012 -0.841774 -1.533123   
93 -1.632349  0.613383 -0.587851  0.467107 -0.387274  0.482249 -1.996139   
94 -0.452214  1.963830 -0.068380 -0.537475 -0.983536 -1.350852 -0.932825   
95  0.535555  0.535315 -0.316394 -1.345825  0.985646 -0.280841  1.692374   
96 -0.208874  0.503362 -0.994804 -1.141338  0.144400 -1.139310 -0.536875   
97 -0.742837  0.068892  0.219607 -1.762436  0.192502 -0.084573  0.081371   
98  0.539002  1.282003 -1.023318  1.905679 -0.839147  1.025434 -1.663809   
99  1.151261  0.472696  0.356989 -0.468862 -0.296073  2.211698  0.407838   

          7         8         9   ...        90        91        92        93  \
90  0.658016 -0.358020 -0.814197  ... -0.542122 -1.109562  0.012807 -1.076481   
91  0.764762  0.079041 -1.180081  ... -1.444890 -1.879220  0.172866  0.062851   
92  0.316225  0.686373  0.649973  ...  1.148693  0.273709  0.113395 -2.012517   
93  0.597855 -0.922183 -0.597533  ... -0.863316 -0.164729  0.066904  0.206859   
94 -0.426861  0.604727  1.543318  ... -0.394486 -0.361045 -0.569295  0.170614   
95  2.236995  0.305292 -0.048202  ...  0.004992 -0.998164 -0.384085 -2.235665   
96  1.049218  1.978938 -0.557667  ... -0.073395 -0.717267  0.750956 -1.429442   
97 -0.119534  1.060109  0.330919  ...  1.211900  0.910360 -1.555058  0.149891   
98  1.280217  0.401399  2.902964  ... -0.748285 -0.963052  0.103504  0.311597   
99  0.415483  0.958924 -0.164693  ... -0.708794  0.409151 -0.033786  0.035134   

          94        95        96        97        98        99  
90 -0.343338 -0.918269 -1.139891 -0.292008  1.041788 -0.478553  
91  0.656325  0.131990 -1.739561 -1.218281  0.761286 -0.585158  
92  0.389897 -1.214232  0.959385  0.691414  0.962048  0.516446  
93 -0.052755 -0.042843  0.864783  1.639371 -0.185498  0.211867  
94 -0.075238 -0.748397  0.982877 -0.405330 -0.959837  0.494697  
95 -1.191961  1.266627  0.505866 -1.204067 -0.017088 -1.493089  
96  0.440364  0.827207 -1.527539  0.554133 -0.432447 -0.978240  
97  1.466277  0.115172  0.853162  0.587283  0.442131 -0.091038  
98  0.899014  0.099926 -0.548970 -0.046887 -1.867753  0.005402  
99  0.555811 -0.346093 -1.671665  0.414849 -0.222663 -0.396319  

[10 rows x 100 columns]

In [100]:
## .loc --> index
## .iloc --> Columns


df.iloc[0:2, 3:6]

3         4         5
0 -1.603644 -0.933890 -0.245013
1  0.392860  2.169864 -0.933146

In [101]:
df.loc[0:2, 3:6]

3         4         5         6
0 -1.603644 -0.933890 -0.245013  0.448170
1  0.392860  2.169864 -0.933146  0.073333
2  0.775636 -1.565388 -2.116412  0.330345

In [102]:
a

{'key1': ['a', 'b', 'c', 'd', 'e', 'f'],
 'key2': [0, 1, 2, 3, 4, 5],
 'key3': ['A', 'B', 'C', 'D', 'E', 'F']}

In [103]:
df = pd.DataFrame(a)

In [104]:
df

key1  key2 key3
0    a     0    A
1    b     1    B
2    c     2    C
3    d     3    D
4    e     4    E
5    f     5    F

In [106]:
df.iloc[0:3, 0:2]

key1  key2
0    a     0
1    b     1
2    c     2

In [108]:
df.loc[0:2, ['key3', 'key2']]

key3  key2
0    A     0
1    B     1
2    C     2

In [109]:
df

key1  key2 key3
0    a     0    A
1    b     1    B
2    c     2    C
3    d     3    D
4    e     4    E
5    f     5    F

In [110]:
df.to_csv('df_from_sc.csv')